### ISSUE TITLE
20 GeV selection code

### ISSUE THREAD

**Issue by rathjd** [BFF-Zprime-mumu/Zprime2muAnalysis#12]
As of the last pull, no 20 GeV preselection of jets is present in the ntuple code, and no 20 GeV selection of b-tagged jets is in the analysis code

### Types of issue

- [ ] Feature: 20 GeV ntuple preselection on jets
- [ ] Feature: 20 GeV analysis b-tagged jet selection
- [ ] Feature: Distinct 30 GeV analysis anti-b-tagged jet selection

## Expected Behavior

Jets with 20 GeV should be stored in the ntuple. In the analysis code, b-tagged jets should pass if >20 GeV and anti-b-tagged jets should pass if >30 GeV

## Current Behavior

Currently, the ntuplising code should select >30 GeV jets only.
The analysis code in the last pulled iteration also selects >30 GeV jets without any b-tagging distinction.

## Context (for feature requests)

It's either an update of the repository to code that already exists, so we can crosscheck it works as expected, or introducing a new feature that's necessary to improve our expected significance.

**Comment by mexanick** [comment]
why should we distinguish b and \bar{b} like that? Or your "anti-b-tagged jets" means jets, which fail to pass the b-tagging selection, i.e. light jets?

**Comment by rathjd** [comment]
@mexanick with anti-b-tagged I meant that they fail the CSV b-tagging criteria.

**Comment by mexanick** [comment]
Implemented
