### ISSUE TITLE
2D plots of b-jet vs !b-jet multiplicity

### ISSUE THREAD

**Issue by rathjd** [BFF-Zprime-mumu/Zprime2muAnalysis#13]
Motivational plots of our choice of jet binning will be needed for signals and backgrounds for presentation purposes.

### Types of issue

- [ ] Feature: 2D plot of number of bottom-tagged jets vs number of anti-"bottom-tagged" jets

## Expected Behavior

Show the number of bottom-tagged vs anti-"bottom-tagged" jets per event for the whole sample after trigger.

**Comment by mexanick** [comment]
Implemented
